default: &default
  encoding: utf8
  adapter: postgresql
  database: eshop_development
  host: localhost
  pool: 5
  username: sushi_new
  password: 1234
#  username: amyalenkov
#  password: 2102

development:
  <<: *default
  database: eshop_development

test:
  <<: *default
  database: eshop_test

production:
  <<: *default
  database: eshop_production
  username: eshop_db
  password: <%= Rails.application.secrets.db_password %>