default: &default 
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8


development: 
  # «: *default
  # database: eshop_development
  adapter: postgresql
  host: localhost
  database: eshop_development
  pool: 5
  # username: amyalenkov
  # password: 2102
  username: sushi
  password: 1234
  encoding: utf8

test: 
  «: *default
  database: eshop_test

production: 
  «: *default
  database: eshop_production
  username: eshop
  password: <%= ENV['ESHOP_DATABASE_PASSWORD'] %>